//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinaGameEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DinaGameEngine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur.
        /// </summary>
        public static string AddColor_ColorPicker_Label {
            get {
                return ResourceManager.GetString("AddColor_ColorPicker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé dans PaletteColors.
        /// </summary>
        public static string AddColor_Key_Label {
            get {
                return ResourceManager.GetString("AddColor_Key_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;une nouvelle couleur.
        /// </summary>
        public static string AddColor_Title {
            get {
                return ResourceManager.GetString("AddColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une couleur.
        /// </summary>
        public static string AddColor_Title_Edit {
            get {
                return ResourceManager.GetString("AddColor_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une item au menu.
        /// </summary>
        public static string AddComponent_MenuItem_Title {
            get {
                return ResourceManager.GetString("AddComponent_MenuItem_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un titre au menu.
        /// </summary>
        public static string AddComponent_MenuTitle_Title {
            get {
                return ResourceManager.GetString("AddComponent_MenuTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;un nouveau texte.
        /// </summary>
        public static string AddComponent_Text_Title {
            get {
                return ResourceManager.GetString("AddComponent_Text_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichiers TTF (*.ttf)|*.ttf.
        /// </summary>
        public static string AddFont_BrowseTtf_File {
            get {
                return ResourceManager.GetString("AddFont_BrowseTtf_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher une police (.ttf).
        /// </summary>
        public static string AddFont_BrowseTtf_Title {
            get {
                return ResourceManager.GetString("AddFont_BrowseTtf_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé dans FontKeys.
        /// </summary>
        public static string AddFont_Key_Label {
            get {
                return ResourceManager.GetString("AddFont_Key_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taille.
        /// </summary>
        public static string AddFont_Size_Label {
            get {
                return ResourceManager.GetString("AddFont_Size_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacement.
        /// </summary>
        public static string AddFont_Spacing_Label {
            get {
                return ResourceManager.GetString("AddFont_Spacing_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        public static string AddFont_Style_Label {
            get {
                return ResourceManager.GetString("AddFont_Style_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;une nouvelle police.
        /// </summary>
        public static string AddFont_Title {
            get {
                return ResourceManager.GetString("AddFont_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifier une police.
        /// </summary>
        public static string AddFont_Title_Edit {
            get {
                return ResourceManager.GetString("AddFont_Title_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier de la police (.ttf).
        /// </summary>
        public static string AddFont_TtfFile_Label {
            get {
                return ResourceManager.GetString("AddFont_TtfFile_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajout d&apos;une nouvelle scène.
        /// </summary>
        public static string AddScene_Title {
            get {
                return ResourceManager.GetString("AddScene_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dina Game Engine.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une couleur.
        /// </summary>
        public static string ColorEditor_AddColor {
            get {
                return ResourceManager.GetString("ColorEditor_AddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleur.
        /// </summary>
        public static string Component_Color_Label {
            get {
                return ResourceManager.GetString("Component_Color_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contenu.
        /// </summary>
        public static string Component_Content_Label {
            get {
                return ResourceManager.GetString("Component_Content_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimensions.
        /// </summary>
        public static string Component_Dimensions_Label {
            get {
                return ResourceManager.GetString("Component_Dimensions_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le champ &apos;{0}&apos; est encore utilisé dans votre code.
        ///Pensez à le supprimer manuellement..
        /// </summary>
        public static string Component_FieldStillUsed_Message {
            get {
                return ResourceManager.GetString("Component_FieldStillUsed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champ encore utilisé.
        /// </summary>
        public static string Component_FieldStillUsed_Title {
            get {
                return ResourceManager.GetString("Component_FieldStillUsed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police.
        /// </summary>
        public static string Component_Font_Label {
            get {
                return ResourceManager.GetString("Component_Font_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement horizontal.
        /// </summary>
        public static string Component_HorizontalAlignment_Label {
            get {
                return ResourceManager.GetString("Component_HorizontalAlignment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé.
        /// </summary>
        public static string Component_Key_Label {
            get {
                return ResourceManager.GetString("Component_Key_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index de l&apos;item sélectionné par défaut.
        /// </summary>
        public static string Component_MenuManager_CurrentItemIndex_Label {
            get {
                return ResourceManager.GetString("Component_MenuManager_CurrentItemIndex_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sens d&apos;affichage des items.
        /// </summary>
        public static string Component_MenuManager_Direction_Label {
            get {
                return ResourceManager.GetString("Component_MenuManager_Direction_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espacement entre les items.
        /// </summary>
        public static string Component_MenuManager_ItemSpacing_Label {
            get {
                return ResourceManager.GetString("Component_MenuManager_ItemSpacing_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Component_Position_Label {
            get {
                return ResourceManager.GetString("Component_Position_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remise à Auto des valeurs.
        /// </summary>
        public static string Component_Reset_Tooltip {
            get {
                return ResourceManager.GetString("Component_Reset_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        public static string Component_Rotation_Label {
            get {
                return ResourceManager.GetString("Component_Rotation_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to État.
        /// </summary>
        public static string Component_State_Label {
            get {
                return ResourceManager.GetString("Component_State_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignement vertical.
        /// </summary>
        public static string Component_VerticalAlignment_Label {
            get {
                return ResourceManager.GetString("Component_VerticalAlignment_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibilité.
        /// </summary>
        public static string Component_Visible_Label {
            get {
                return ResourceManager.GetString("Component_Visible_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZOrder.
        /// </summary>
        public static string Component_ZOrder_Label {
            get {
                return ResourceManager.GetString("Component_ZOrder_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer de la liste.
        /// </summary>
        public static string ContextMenu_RemoveFromList {
            get {
                return ResourceManager.GetString("ContextMenu_RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désépingler.
        /// </summary>
        public static string ContextMenu_Unpin {
            get {
                return ResourceManager.GetString("ContextMenu_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet &apos;{0}&apos; en cours de création....
        /// </summary>
        public static string CreatingProject_Message {
            get {
                return ResourceManager.GetString("CreatingProject_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet &apos;{0}&apos; créé avec succès..
        /// </summary>
        public static string CreatingProject_Success {
            get {
                return ResourceManager.GetString("CreatingProject_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Création du projet.
        /// </summary>
        public static string CreatingProject_Title {
            get {
                return ResourceManager.GetString("CreatingProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string Dialog_Add {
            get {
                return ResourceManager.GetString("Dialog_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appliquer.
        /// </summary>
        public static string Dialog_Apply {
            get {
                return ResourceManager.GetString("Dialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        public static string Dialog_Open {
            get {
                return ResourceManager.GetString("Dialog_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un projet.
        /// </summary>
        public static string Dialog_OpenProject {
            get {
                return ResourceManager.GetString("Dialog_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oui.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur est survenue lors de la création du nouveau projet..
        /// </summary>
        public static string Error_NewProject {
            get {
                return ResourceManager.GetString("Error_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier &apos;{0}&apos; n&apos;existe pas dans le répertoire sélectionné..
        /// </summary>
        public static string Error_OpenProject {
            get {
                return ResourceManager.GetString("Error_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une police.
        /// </summary>
        public static string FontEditor_AddFont {
            get {
                return ResourceManager.GetString("FontEditor_AddFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clé existe déjà. Veuillez en choisir une autre..
        /// </summary>
        public static string Key_AlreadyExist {
            get {
                return ResourceManager.GetString("Key_AlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé requise.
        /// </summary>
        public static string Key_Required {
            get {
                return ResourceManager.GetString("Key_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choisissez la langue par défaut du projet.
        /// </summary>
        public static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langue par défaut.
        /// </summary>
        public static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valider.
        /// </summary>
        public static string Language_Validate {
            get {
                return ResourceManager.GetString("Language_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fichier.
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer toutes les vues.
        /// </summary>
        public static string MainMenu_File_CloseAllViews {
            get {
                return ResourceManager.GetString("MainMenu_File_CloseAllViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer le projet.
        /// </summary>
        public static string MainMenu_File_CloseProject {
            get {
                return ResourceManager.GetString("MainMenu_File_CloseProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer la vue.
        /// </summary>
        public static string MainMenu_File_CloseView {
            get {
                return ResourceManager.GetString("MainMenu_File_CloseView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau projet.
        /// </summary>
        public static string MainMenu_File_NewProject {
            get {
                return ResourceManager.GetString("MainMenu_File_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir un projet.
        /// </summary>
        public static string MainMenu_File_OpenProject {
            get {
                return ResourceManager.GetString("MainMenu_File_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quitter.
        /// </summary>
        public static string MainMenu_File_Quit {
            get {
                return ResourceManager.GetString("MainMenu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet &apos;{0}&apos; a été sauvegardé avec succès..
        /// </summary>
        public static string MainMenu_File_Save_Message {
            get {
                return ResourceManager.GetString("MainMenu_File_Save_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarde du projet &apos;{0}&apos;.
        /// </summary>
        public static string MainMenu_File_Save_Title {
            get {
                return ResourceManager.GetString("MainMenu_File_Save_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder le projet.
        /// </summary>
        public static string MainMenu_File_SaveProject {
            get {
                return ResourceManager.GetString("MainMenu_File_SaveProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aide.
        /// </summary>
        public static string MainMenu_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos....
        /// </summary>
        public static string MainMenu_Help_About {
            get {
                return ResourceManager.GetString("MainMenu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelles.
        /// </summary>
        public static string MainMenu_Help_News {
            get {
                return ResourceManager.GetString("MainMenu_Help_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projet.
        /// </summary>
        public static string MainMenu_Project {
            get {
                return ResourceManager.GetString("MainMenu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une couleur....
        /// </summary>
        public static string MainMenu_Project_AddColor {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une police....
        /// </summary>
        public static string MainMenu_Project_AddFont {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une image....
        /// </summary>
        public static string MainMenu_Project_AddImage {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter une scène....
        /// </summary>
        public static string MainMenu_Project_AddScene {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter un son....
        /// </summary>
        public static string MainMenu_Project_AddSound {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outils.
        /// </summary>
        public static string MainMenu_Tools {
            get {
                return ResourceManager.GetString("MainMenu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transitions entre scènes.
        /// </summary>
        public static string MainMenu_Tools_Transitions {
            get {
                return ResourceManager.GetString("MainMenu_Tools_Transitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fenêtre.
        /// </summary>
        public static string MainMenu_Window {
            get {
                return ResourceManager.GetString("MainMenu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de composants :.
        /// </summary>
        public static string MainWindow_Scene_Components {
            get {
                return ResourceManager.GetString("MainWindow_Scene_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du projet.
        /// </summary>
        public static string Marker_ProjectName {
            get {
                return ResourceManager.GetString("Marker_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espace de nom racine.
        /// </summary>
        public static string Marker_RootNamespace {
            get {
                return ResourceManager.GetString("Marker_RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la solution.
        /// </summary>
        public static string Marker_SolutionName {
            get {
                return ResourceManager.GetString("Marker_SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        public static string Markers_Create {
            get {
                return ResourceManager.GetString("Markers_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet sera créé dans :.
        /// </summary>
        public static string Markers_FolderPreview {
            get {
                return ResourceManager.GetString("Markers_FolderPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libellé.
        /// </summary>
        public static string Markers_LabelHeader {
            get {
                return ResourceManager.GetString("Markers_LabelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Markers_Previous {
            get {
                return ResourceManager.GetString("Markers_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation des marqueurs.
        /// </summary>
        public static string Markers_Title {
            get {
                return ResourceManager.GetString("Markers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valeur.
        /// </summary>
        public static string Markers_ValueHeader {
            get {
                return ResourceManager.GetString("Markers_ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sons/SFX.
        /// </summary>
        public static string Nav_Audio {
            get {
                return ResourceManager.GetString("Nav_Audio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couleurs.
        /// </summary>
        public static string Nav_Colors {
            get {
                return ResourceManager.GetString("Nav_Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polices.
        /// </summary>
        public static string Nav_Fonts {
            get {
                return ResourceManager.GetString("Nav_Fonts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string Nav_Images {
            get {
                return ResourceManager.GetString("Nav_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrôles.
        /// </summary>
        public static string Nav_Inputs {
            get {
                return ResourceManager.GetString("Nav_Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localisation.
        /// </summary>
        public static string Nav_Localization {
            get {
                return ResourceManager.GetString("Nav_Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paramètres par défaut du projet.
        /// </summary>
        public static string Nav_ProjectDefaultSettings {
            get {
                return ResourceManager.GetString("Nav_ProjectDefaultSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parcourir....
        /// </summary>
        public static string NewProject_Browse {
            get {
                return ResourceManager.GetString("NewProject_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string NewProject_Cancel {
            get {
                return ResourceManager.GetString("NewProject_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement.
        /// </summary>
        public static string NewProject_Location {
            get {
                return ResourceManager.GetString("NewProject_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du projet.
        /// </summary>
        public static string NewProject_Name {
            get {
                return ResourceManager.GetString("NewProject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string NewProject_Next {
            get {
                return ResourceManager.GetString("NewProject_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le projet sera créé dans :.
        /// </summary>
        public static string NewProject_Preview {
            get {
                return ResourceManager.GetString("NewProject_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau projet.
        /// </summary>
        public static string NewProject_Title {
            get {
                return ResourceManager.GetString("NewProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de supprimer la scène &apos;{0}&apos;.
        ///Cela supprimera :
        ///- les fichiers &apos;{1}.Designer.cs&apos; et &apos;{1}.cs&apos;
        ///- la clé &apos;{2}&apos; du fichier SceneKeys
        ///- l&apos;enregistrement de la scène dans le fichier principal du projet
        ///
        ///Voulez-vous tout de même supprimer la scène &apos;{0}&apos; ?.
        /// </summary>
        public static string SceneDelete_Confirmation {
            get {
                return ResourceManager.GetString("SceneDelete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppression de la scène &apos;{0}&apos;.
        /// </summary>
        public static string SceneDelete_Confirmation_Title {
            get {
                return ResourceManager.GetString("SceneDelete_Confirmation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la classe :.
        /// </summary>
        public static string SceneName_ClassName {
            get {
                return ResourceManager.GetString("SceneName_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clé :.
        /// </summary>
        public static string SceneName_Key {
            get {
                return ResourceManager.GetString("SceneName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de la scène :.
        /// </summary>
        public static string SceneName_Label {
            get {
                return ResourceManager.GetString("SceneName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernier accès :.
        /// </summary>
        public static string Startup_LastAccess {
            get {
                return ResourceManager.GetString("Startup_LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La semaine dernière.
        /// </summary>
        public static string Startup_LastWeek {
            get {
                return ResourceManager.GetString("Startup_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau projet.
        /// </summary>
        public static string Startup_NewProject {
            get {
                return ResourceManager.GetString("Startup_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plus anciens.
        /// </summary>
        public static string Startup_Older {
            get {
                return ResourceManager.GetString("Startup_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir....
        /// </summary>
        public static string Startup_Open {
            get {
                return ResourceManager.GetString("Startup_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Épinglés.
        /// </summary>
        public static string Startup_Pinned {
            get {
                return ResourceManager.GetString("Startup_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce mois-ci.
        /// </summary>
        public static string Startup_ThisMonth {
            get {
                return ResourceManager.GetString("Startup_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette semaine.
        /// </summary>
        public static string Startup_ThisWeek {
            get {
                return ResourceManager.GetString("Startup_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aujourd&apos;hui.
        /// </summary>
        public static string Startup_Today {
            get {
                return ResourceManager.GetString("Startup_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier.
        /// </summary>
        public static string Startup_Yesterday {
            get {
                return ResourceManager.GetString("Startup_Yesterday", resourceCulture);
            }
        }
    }
}
