//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinaGameEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DinaGameEngine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dina Game Engine.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un projet.
        /// </summary>
        public static string Dialog_OpenProject {
            get {
                return ResourceManager.GetString("Dialog_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la création du nouveau projet..
        /// </summary>
        public static string Error_NewProject {
            get {
                return ResourceManager.GetString("Error_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier &apos;{0}&apos; n&apos;existe pas dans le répertoire sélectionné..
        /// </summary>
        public static string Error_OpenProject {
            get {
                return ResourceManager.GetString("Error_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir....
        /// </summary>
        public static string NewProject_Browse {
            get {
                return ResourceManager.GetString("NewProject_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string NewProject_Cancel {
            get {
                return ResourceManager.GetString("NewProject_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string NewProject_Create {
            get {
                return ResourceManager.GetString("NewProject_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emplacement.
        /// </summary>
        public static string NewProject_Location {
            get {
                return ResourceManager.GetString("NewProject_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du projet.
        /// </summary>
        public static string NewProject_Name {
            get {
                return ResourceManager.GetString("NewProject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet sera créé dans :.
        /// </summary>
        public static string NewProject_Preview {
            get {
                return ResourceManager.GetString("NewProject_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau projet.
        /// </summary>
        public static string NewProject_Title {
            get {
                return ResourceManager.GetString("NewProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La semaine dernière.
        /// </summary>
        public static string Startup_LastWeek {
            get {
                return ResourceManager.GetString("Startup_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau projet.
        /// </summary>
        public static string Startup_NewProject {
            get {
                return ResourceManager.GetString("Startup_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus anciens.
        /// </summary>
        public static string Startup_Older {
            get {
                return ResourceManager.GetString("Startup_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir....
        /// </summary>
        public static string Startup_OpenProject {
            get {
                return ResourceManager.GetString("Startup_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Épinglés.
        /// </summary>
        public static string Startup_Pinned {
            get {
                return ResourceManager.GetString("Startup_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mois-ci.
        /// </summary>
        public static string Startup_ThisMonth {
            get {
                return ResourceManager.GetString("Startup_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette semaine.
        /// </summary>
        public static string Startup_ThisWeek {
            get {
                return ResourceManager.GetString("Startup_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aujourd&apos;hui.
        /// </summary>
        public static string Startup_Today {
            get {
                return ResourceManager.GetString("Startup_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hier.
        /// </summary>
        public static string Startup_Yesterday {
            get {
                return ResourceManager.GetString("Startup_Yesterday", resourceCulture);
            }
        }
    }
}
