//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinaGameEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DinaGameEngine.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dina Game Engine.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer de la liste.
        /// </summary>
        public static string ContextMenu_RemoveFromList {
            get {
                return ResourceManager.GetString("ContextMenu_RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désépingler.
        /// </summary>
        public static string ContextMenu_Unpin {
            get {
                return ResourceManager.GetString("ContextMenu_Unpin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet &apos;{0}&apos; en cours de création....
        /// </summary>
        public static string CreatingProject_Message {
            get {
                return ResourceManager.GetString("CreatingProject_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet &apos;{0}&apos; créé avec succès..
        /// </summary>
        public static string CreatingProject_Success {
            get {
                return ResourceManager.GetString("CreatingProject_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Création du projet.
        /// </summary>
        public static string CreatingProject_Title {
            get {
                return ResourceManager.GetString("CreatingProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter.
        /// </summary>
        public static string Dialog_Add {
            get {
                return ResourceManager.GetString("Dialog_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Non.
        /// </summary>
        public static string Dialog_No {
            get {
                return ResourceManager.GetString("Dialog_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        public static string Dialog_OK {
            get {
                return ResourceManager.GetString("Dialog_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir un projet.
        /// </summary>
        public static string Dialog_OpenProject {
            get {
                return ResourceManager.GetString("Dialog_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Oui.
        /// </summary>
        public static string Dialog_Yes {
            get {
                return ResourceManager.GetString("Dialog_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur est survenue lors de la création du nouveau projet..
        /// </summary>
        public static string Error_NewProject {
            get {
                return ResourceManager.GetString("Error_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier &apos;{0}&apos; n&apos;existe pas dans le répertoire sélectionné..
        /// </summary>
        public static string Error_OpenProject {
            get {
                return ResourceManager.GetString("Error_OpenProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez la langue par défaut du projet.
        /// </summary>
        public static string Language_Label {
            get {
                return ResourceManager.GetString("Language_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Langue par défaut.
        /// </summary>
        public static string Language_Title {
            get {
                return ResourceManager.GetString("Language_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valider.
        /// </summary>
        public static string Language_Validate {
            get {
                return ResourceManager.GetString("Language_Validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fichier.
        /// </summary>
        public static string MainMenu_File {
            get {
                return ResourceManager.GetString("MainMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fermer.
        /// </summary>
        public static string MainMenu_File_Close {
            get {
                return ResourceManager.GetString("MainMenu_File_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau projet.
        /// </summary>
        public static string MainMenu_File_NewProject {
            get {
                return ResourceManager.GetString("MainMenu_File_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir.
        /// </summary>
        public static string MainMenu_File_Open {
            get {
                return ResourceManager.GetString("MainMenu_File_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        public static string MainMenu_File_Quit {
            get {
                return ResourceManager.GetString("MainMenu_File_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string MainMenu_File_Save {
            get {
                return ResourceManager.GetString("MainMenu_File_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aide.
        /// </summary>
        public static string MainMenu_Help {
            get {
                return ResourceManager.GetString("MainMenu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à À propos....
        /// </summary>
        public static string MainMenu_Help_About {
            get {
                return ResourceManager.GetString("MainMenu_Help_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouvelles.
        /// </summary>
        public static string MainMenu_Help_News {
            get {
                return ResourceManager.GetString("MainMenu_Help_News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Projet.
        /// </summary>
        public static string MainMenu_Project {
            get {
                return ResourceManager.GetString("MainMenu_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une police....
        /// </summary>
        public static string MainMenu_Project_AddFont {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une image....
        /// </summary>
        public static string MainMenu_Project_AddImage {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter une scène....
        /// </summary>
        public static string MainMenu_Project_AddScene {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ajouter un son....
        /// </summary>
        public static string MainMenu_Project_AddSound {
            get {
                return ResourceManager.GetString("MainMenu_Project_AddSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outils.
        /// </summary>
        public static string MainMenu_Tools {
            get {
                return ResourceManager.GetString("MainMenu_Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transitions entre scènes.
        /// </summary>
        public static string MainMenu_Tools_Transitions {
            get {
                return ResourceManager.GetString("MainMenu_Tools_Transitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fenêtre.
        /// </summary>
        public static string MainMenu_Window {
            get {
                return ResourceManager.GetString("MainMenu_Window", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du projet.
        /// </summary>
        public static string Marker_ProjectName {
            get {
                return ResourceManager.GetString("Marker_ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Espace de nom racine.
        /// </summary>
        public static string Marker_RootNamespace {
            get {
                return ResourceManager.GetString("Marker_RootNamespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la solution.
        /// </summary>
        public static string Marker_SolutionName {
            get {
                return ResourceManager.GetString("Marker_SolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer.
        /// </summary>
        public static string Markers_Create {
            get {
                return ResourceManager.GetString("Markers_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet sera créé dans :.
        /// </summary>
        public static string Markers_FolderPreview {
            get {
                return ResourceManager.GetString("Markers_FolderPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Libellé.
        /// </summary>
        public static string Markers_LabelHeader {
            get {
                return ResourceManager.GetString("Markers_LabelHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Précédent.
        /// </summary>
        public static string Markers_Previous {
            get {
                return ResourceManager.GetString("Markers_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Validation des marqueurs.
        /// </summary>
        public static string Markers_Title {
            get {
                return ResourceManager.GetString("Markers_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Valeur.
        /// </summary>
        public static string Markers_ValueHeader {
            get {
                return ResourceManager.GetString("Markers_ValueHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parcourir....
        /// </summary>
        public static string NewProject_Browse {
            get {
                return ResourceManager.GetString("NewProject_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string NewProject_Cancel {
            get {
                return ResourceManager.GetString("NewProject_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Emplacement.
        /// </summary>
        public static string NewProject_Location {
            get {
                return ResourceManager.GetString("NewProject_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom du projet.
        /// </summary>
        public static string NewProject_Name {
            get {
                return ResourceManager.GetString("NewProject_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string NewProject_Next {
            get {
                return ResourceManager.GetString("NewProject_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le projet sera créé dans :.
        /// </summary>
        public static string NewProject_Preview {
            get {
                return ResourceManager.GetString("NewProject_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau projet.
        /// </summary>
        public static string NewProject_Title {
            get {
                return ResourceManager.GetString("NewProject_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la classe :.
        /// </summary>
        public static string SceneName_ClassName {
            get {
                return ResourceManager.GetString("SceneName_ClassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clé :.
        /// </summary>
        public static string SceneName_Key {
            get {
                return ResourceManager.GetString("SceneName_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom de la scène :.
        /// </summary>
        public static string SceneName_Label {
            get {
                return ResourceManager.GetString("SceneName_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dernier accès :.
        /// </summary>
        public static string Startup_LastAccess {
            get {
                return ResourceManager.GetString("Startup_LastAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La semaine dernière.
        /// </summary>
        public static string Startup_LastWeek {
            get {
                return ResourceManager.GetString("Startup_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nouveau projet.
        /// </summary>
        public static string Startup_NewProject {
            get {
                return ResourceManager.GetString("Startup_NewProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Plus anciens.
        /// </summary>
        public static string Startup_Older {
            get {
                return ResourceManager.GetString("Startup_Older", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ouvrir....
        /// </summary>
        public static string Startup_Open {
            get {
                return ResourceManager.GetString("Startup_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Épinglés.
        /// </summary>
        public static string Startup_Pinned {
            get {
                return ResourceManager.GetString("Startup_Pinned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce mois-ci.
        /// </summary>
        public static string Startup_ThisMonth {
            get {
                return ResourceManager.GetString("Startup_ThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette semaine.
        /// </summary>
        public static string Startup_ThisWeek {
            get {
                return ResourceManager.GetString("Startup_ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aujourd&apos;hui.
        /// </summary>
        public static string Startup_Today {
            get {
                return ResourceManager.GetString("Startup_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hier.
        /// </summary>
        public static string Startup_Yesterday {
            get {
                return ResourceManager.GetString("Startup_Yesterday", resourceCulture);
            }
        }
    }
}
