using DinaGameEngine.Abstractions;
using DinaGameEngine.Common;
using DinaGameEngine.Models;

using System.Text;

namespace DinaGameEngine.CodeGeneration
{
    public partial class CodeGenerator
    {
        private void GenerateGameProjectDesigner(GameProjectModel gameProjectModel)
        {
            var projectDesignerFilePath = _fileService.Combine(gameProjectModel.RootPath, gameProjectModel.ProjectName, $"{gameProjectModel.ProjectName}.Designer.cs");
            if (_fileService.FileExists(projectDesignerFilePath) && !_generatedFileChecker.IsAutoGenerated(projectDesignerFilePath))
            {
                _logService.Warning($"Fichier '{projectDesignerFilePath}' modifié par l'utilisateur.");
                return;
            }

            var generatedFile = new StringBuilder();
            // Génère le contenu : header, champs, constructeur, méthodes du cycle de vie, méthodes d'initialisation, RegisterScene, méthodes partielles
            generatedFile.AppendLine(CodeBuilder.AddAutoGeneratedTag());
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:USINGS]=", 0));
            var usings = new string[]
            {
                "DinaCSharp.Inputs",
                "DinaCSharp.Resources",
                "DinaCSharp.Services",
                "DinaCSharp.Services.Audio",
                "DinaCSharp.Services.Fonts",
                "DinaCSharp.Services.Localization",
                "DinaCSharp.Services.Save",
                "DinaCSharp.Services.Scenes",
                "DinaCSharp.Services.Screen",
                "Microsoft.Xna.Framework",
                "Microsoft.Xna.Framework.Graphics",
                "Microsoft.Xna.Framework.Input",
                "System.Linq",
                $"{gameProjectModel.RootNamespace}.Core.Datas",
                $"{gameProjectModel.RootNamespace}.Core.Keys",
                $"{gameProjectModel.RootNamespace}.Scenes",
            };
            foreach (var ns in usings)
                generatedFile.AppendLine(CodeBuilder.AddUsing(ns));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:USINGS]=", 0));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}", 0));

            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class {gameProjectModel.ProjectName} : Game", 1));

            // Ajout des champs privées
            generatedFile.AppendLine(CodeBuilder.AddLine("private readonly GraphicsDeviceManager _graphics;", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("private SpriteBatch _spriteBatch;", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("private SceneManager _sceneManager;", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("private bool _isReadyToDraw;", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public {gameProjectModel.ProjectName}()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("_graphics = new GraphicsDeviceManager(this);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("Content.RootDirectory = \"Content\";", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("IsMouseVisible = true;", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("OnInitialize();", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void OnInitialize()", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());


            generatedFile.AppendLine(CodeBuilder.OpenBlock("protected override void Initialize()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("InitializeScreenManager();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("InitializeConfig();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("InitializeFontManager();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("InitializeSceneManager();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("InitializeInputManager();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("RegisterServices();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ApplyConfiguration();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("base.Initialize();", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("protected override void LoadContent()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("_spriteBatch = new SpriteBatch(GraphicsDevice);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("RegisterScene();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("OnSetStartupScene();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("_isReadyToDraw = true;", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void OnSetStartupScene()", 2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("protected override void Update(GameTime gameTime)", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("_sceneManager.Update(gameTime);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("base.Update(gameTime);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("protected override void Draw(GameTime gameTime)", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("if (!_isReadyToDraw)", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("return;", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("GraphicsDevice.Clear(BackgroundColor);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("_sceneManager.Draw(_spriteBatch, true);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("base.Draw(gameTime);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.AddLine("partial Color BackgroundColor { get; }", 2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private void InitializeScreenManager()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("var screenManager = ScreenManager.Initialize(_graphics, Window);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ScreenManager.SetAllowedResolutions([", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("new Point(1280, 720),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("new Point(1600, 900),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("new Point(1920, 1080),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("new Point(2560, 1440),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("new Point(3840, 2160)", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("]);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("screenManager.Register(DinaServiceKeys.ScreenManager);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private void InitializeSceneManager()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("_sceneManager = SceneManager.InitializeAndRegister(this);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private void InitializeFontManager()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("var fontManager = FontManager.Initialize(Services, \"FontContent\",", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("[", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("new ResolutionFontInfo(ResolutionKeys.R720p, new Point(1280, 720), \"_720p\"),", 5));
            generatedFile.AppendLine(CodeBuilder.AddLine("new ResolutionFontInfo(ResolutionKeys.R900p, new Point(1600, 900), \"_900p\"),", 5));
            generatedFile.AppendLine(CodeBuilder.AddLine("new ResolutionFontInfo(ResolutionKeys.R1080p, new Point(1920, 1080), \"_1080p\"),", 5));
            generatedFile.AppendLine(CodeBuilder.AddLine("new ResolutionFontInfo(ResolutionKeys.R1440p, new Point(2560, 1440), \"_1440p\"),", 5));
            generatedFile.AppendLine(CodeBuilder.AddLine("new ResolutionFontInfo(ResolutionKeys.R2160p, new Point(3840, 2160), \"_2160p\")", 5));
            generatedFile.AppendLine(CodeBuilder.AddLine("],", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("ResolutionKeys.R1080p);", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("fontManager.Register(DinaServiceKeys.FontManager);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private static void InitializeConfig()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("var dpMaxResolution = ScreenManager.AvailableResolutions.ToList().Last();", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("Point maxResolution = new Point(dpMaxResolution.Width, dpMaxResolution.Height);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("var defaultConfig = new DefaultConfigData(maxResolution, true);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ServiceLocator.Register(ServiceKeys.DefaultConfig, defaultConfig);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("var configData = SaveManager.LoadObjectFromEncryptFile<ConfigData>(ServiceKeys.Config.Value) ?? defaultConfig;", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ServiceLocator.Register(ServiceKeys.Config, configData);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private static void InitializeInputManager()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("var playerController = InputManager.RegisterPlayer(PlayerIndex.One,", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("(PlayerInputKeys.Up, new ControllerKey[] { new KeyboardControllerKey(Keys.Up), new GamepadControllerKey(Buttons.LeftThumbstickUp) }),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("(PlayerInputKeys.Down, new ControllerKey[] { new KeyboardControllerKey(Keys.Down), new GamepadControllerKey(Buttons.LeftThumbstickDown) }),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("(PlayerInputKeys.Left, new ControllerKey[] { new KeyboardControllerKey(Keys.Left), new GamepadControllerKey(Buttons.LeftThumbstickLeft) }),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("(PlayerInputKeys.Right, new ControllerKey[] { new KeyboardControllerKey(Keys.Right), new GamepadControllerKey(Buttons.LeftThumbstickRight) }),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("(PlayerInputKeys.Activate, new ControllerKey[] { new KeyboardControllerKey(Keys.Enter), new GamepadControllerKey(Buttons.A) }),", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine("(PlayerInputKeys.Cancel, new ControllerKey[] { new KeyboardControllerKey(Keys.Back), new GamepadControllerKey(Buttons.B) })", 4));
            generatedFile.AppendLine(CodeBuilder.AddLine(");", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ServiceLocator.Register(ServiceKeys.PlayerController, playerController);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private void RegisterServices()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("ServiceLocator.Register(ServiceKeys.SoundManager, new SoundManager(this, \"AudioContent\"));", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ResourceManager assetsResourceManager = new ResourceManager(Services, \"AssetsContent\");", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ServiceLocator.Register(ServiceKeys.AssetsResourceManager, assetsResourceManager);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private static void ApplyConfiguration()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("ConfigData configData = ServiceLocator.Get<ConfigData>(ServiceKeys.Config);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("ScreenManager screenManager = ServiceLocator.Get<ScreenManager>(DinaServiceKeys.ScreenManager);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("SoundManager soundManager = ServiceLocator.Get<SoundManager>(DinaServiceKeys.SoundManager);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("screenManager.SetResolution(configData.ResolutionWidth, configData.ResolutionHeight);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("screenManager.SetFullScreen(configData.Fullscreen);", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("soundManager.MasterVolume = configData.MasterVolume / 100;", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("soundManager.MusicVolume = configData.MusicVolume / 100;", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("soundManager.GlobalSoundVolume = configData.SoundsVolume / 100;", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.OpenBlock("private void RegisterScene()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:REGISTER_SCENE]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:REGISTER_SCENE]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("RegisterAdditionalScenes();", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void RegisterAdditionalScenes();", 2));

            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(projectDesignerFilePath, generatedFile.ToString());
            _logService.Info($"Fichier '{gameProjectModel.ProjectName}.Designer.cs' généré.");
        }
        private void GenerateGameProjectUserFile(GameProjectModel gameProjectModel)
        {
            var projectUserFilePath = _fileService.Combine(gameProjectModel.RootPath, gameProjectModel.ProjectName, $"{gameProjectModel.ProjectName}.cs");
            if (_fileService.FileExists(projectUserFilePath))
            {
                _logService.Warning($"Fichier '{projectUserFilePath}' existant.");
                return;
            }

            var generatedFile = new StringBuilder();
            var usings = new string[]
            {
                "Microsoft.Xna.Framework",
                $"{gameProjectModel.RootNamespace}.Core.Keys",
            };
            foreach (var ns in usings)
                generatedFile.AppendLine(CodeBuilder.AddUsing(ns));

            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}", 0));

            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class {gameProjectModel.ProjectName}", 1));

            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void OnInitialize()", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void RegisterAdditionalScenes()", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            generatedFile.AppendLine(CodeBuilder.AddLine("partial Color BackgroundColor => Color.Black;", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void OnSetStartupScene()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("_sceneManager.SetCurrentScene(SceneKeys.MainMenuScene);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));


            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(projectUserFilePath, generatedFile.ToString());
            _logService.Info($"Fichier '{gameProjectModel.ProjectName}.cs' généré.");
        }

        public void UpdateStartupScene(GameProjectModel gameProjectModel)
        {
            var projectUserFilePath = _fileService.Combine(gameProjectModel.RootPath, gameProjectModel.ProjectName, $"{gameProjectModel.ProjectName}.cs");
            var sectionParser = CreateSectionParserFor(projectUserFilePath);

            var startupScene = gameProjectModel.Scenes.FirstOrDefault(s => s.IsStartup);
            if (startupScene == null && gameProjectModel.Scenes.Count > 0)
            {
                _logService.Error("Aucune scène n'a été définie comme scène par défaut.");
                _dialogService.ShowError(LocalizationManager.GetTranslation("DefaultSceneMissing_Title"),
                                         LocalizationManager.GetTranslation("DefaultSceneMissing_Message"));
                return;
            }
            sectionParser.UpdateStartupScene(startupScene!.Key);
            _fileService.WriteAllText(projectUserFilePath, sectionParser.GetContent());
            _logService.Info($"Fichier '{gameProjectModel.ProjectName}.cs' mis à jour avec la scène de départ.");
        }
        public void RemoveStartupScene(GameProjectModel gameProjectModel)
        {
            var projectUserFilePath = _fileService.Combine(gameProjectModel.RootPath, gameProjectModel.ProjectName, $"{gameProjectModel.ProjectName}.cs");
            var sectionParser = CreateSectionParserFor(projectUserFilePath);

            sectionParser.RemoveStartupScene();
            _fileService.WriteAllText(projectUserFilePath, sectionParser.GetContent());
            _logService.Info($"Fichier '{gameProjectModel.ProjectName}.cs' mis à jour (suppression de la scène de départ).");
        }
    }
}
