using DinaGameEngine.Models;
using DinaGameEngine.Models.Project;

using System.Text;


namespace DinaGameEngine.CodeGeneration
{
    public partial class CodeGenerator
    {
        public void GenerateFontKeys(GameProjectModel gameProjectModel)
        {
            GenerateFontKeysDesigner(gameProjectModel);
            GenerateFontKeysUserFile(gameProjectModel);
        }
        public void AddFont(GameProjectModel gameProjectModel, FontModel model)
        {
            GenerateSpriteFontFiles(gameProjectModel, model);

            var designerFilePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "FontKeys.Designer.cs");
            var sectionParser = CreateSectionParserFor(designerFilePath);
            sectionParser.InsertBeforeZone("FONT_KEYS", [$"{CodeBuilder.Indentation(2)}public static readonly Key<FontTag> {model.Key} = Key<FontTag>.FromString(\"{model.Key}\");"]);
            _fileService.WriteAllText(designerFilePath, sectionParser.GetContent());
        }
        public void RemoveFont(GameProjectModel gameProjectModel, FontModel model)
        {
            var designerFilePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "FontKeys.Designer.cs");
            var sectionParser = CreateSectionParserFor(designerFilePath);
            sectionParser.RemoveFromZone("FONT_KEYS", model.Key);
            _fileService.WriteAllText(designerFilePath, sectionParser.GetContent());

            foreach (var path in _resolutionPath)
                UpdateMgcbFile(gameProjectModel, path, $"{model.Key}.spritefont", false);

            RemoveSpriteFonts(gameProjectModel, model);
        }
        private void GenerateFontKeysDesigner(GameProjectModel gameProjectModel)
        {
            var filePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "FontKeys.Designer.cs");
            if (_fileService.FileExists(filePath) && !_generatedFileChecker.IsAutoGenerated(filePath))
            {
                _logService.Warning($"Fichier '{filePath}' modifié par l'utilisateur.");
                return;
            }

            var generatedFile = new StringBuilder();
            generatedFile.AppendLine(CodeBuilder.AddAutoGeneratedTag());
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Using
            generatedFile.AppendLine(CodeBuilder.AddUsing("DinaCSharp.Services"));
            generatedFile.AppendLine(CodeBuilder.AddUsing("DinaCSharp.Services.Fonts"));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Namespace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Core.Keys", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class FontKeys", 1));

            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:FONT_KEYS]=", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:FONT_KEYS]=", 2));

            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(filePath, generatedFile.ToString());
            _logService.Info($"Fichier 'FontKeys.Designer.cs' généré.");
        }
        private void GenerateFontKeysUserFile(GameProjectModel gameProjectModel)
        {
            var filePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "FontKeys.cs");
            if (_fileService.FileExists(filePath))
            {
                _logService.Warning($"Fichier '{filePath}' déjà existant.");
                return;
            }

            var generatedFile = new StringBuilder();

            //Using
            generatedFile.AppendLine(CodeBuilder.AddUsing("DinaCSharp.Services"));
            generatedFile.AppendLine(CodeBuilder.AddUsing("DinaCSharp.Services.Fonts"));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            // Namespace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Core.Keys", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class FontKeys", 1));

            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.AddLine("", 2));


            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(filePath, generatedFile.ToString());
            _logService.Info($"Fichier 'FontKeys.cs' généré.");
        }

        private void GenerateSpriteFontFiles(GameProjectModel gameProjectModel, FontModel model)
        {
            // On vérifie si la police existe déjà dans un des répertoires
            var isFontAlreadyExist = false;
            foreach (var path in _resolutionPath)
            {
                var fileFullName = _fileService.Combine(gameProjectModel.RootPath, "Fonts", "FontContent", path, $"{model.Key}.spritefont");
                if (_fileService.FileExists(fileFullName))
                {
                    _logService.Error($"Fichier '{fileFullName}' déjà existant.");
                    isFontAlreadyExist = true;
                    break;
                }
            }
            // Si la police n'existe pas, on crée les 5 fichiers .spritefont.
            if (!isFontAlreadyExist)
            {
                foreach (var path in _resolutionPath)
                    GenerateSpriteFont(gameProjectModel, path, model);
            }
        }
        private void GenerateSpriteFont(GameProjectModel gameProjectModel, string fontPath, FontModel model)
        {
            var fileFullName = _fileService.Combine(gameProjectModel.RootPath, "Fonts", "FontContent", fontPath, $"{model.Key}.spritefont");

            var adjustedSize = GetSizeForResolution(fontPath, model.Size);
            var spritefontContent = string.Format(CodeBuilder.SpritefontContent(), model.TtfRelativePath, adjustedSize, model.Spacing, model.Style);

            _fileService.WriteAllText(fileFullName, spritefontContent);

            UpdateCharacterRegion(fileFullName);

            UpdateMgcbFile(gameProjectModel, fontPath, _fileService.GetFileName(fileFullName), true);
        }
        private void RemoveSpriteFonts(GameProjectModel gameProjectModel, FontModel model)
        {
            foreach (var path in _resolutionPath)
            {
                var fileFullName = _fileService.Combine(gameProjectModel.RootPath, "Fonts", "FontContent", path, $"{model.Key}.spritefont");
                if (_fileService.FileExists(fileFullName))
                    _fileService.DeleteFile(fileFullName);
            }
            _logService.Info($"Suppression de la police '{model.Key}' effectuée.");
        }
        private void UpdateMgcbFile(GameProjectModel gameProjectModel, string path, string name, bool add)
        {
            var spritefontContentPath = _fileService.Combine(path, name).Replace('\\', '/');
            var fontContentMgcbFile = _fileService.Combine(gameProjectModel.RootPath, "Fonts", "FontContent", "FontContent.mgcb");

            // Vérification si le fichier .spritefont est déjà existant
            var fontContentMgcbFileContent = _fileService.ReadAllText(fontContentMgcbFile);
            var mgcbContent = string.Format(CodeBuilder.MgcbFontContent(), spritefontContentPath, Environment.NewLine);
            if (add && !fontContentMgcbFileContent.Contains(spritefontContentPath))
            {
                _fileService.AppendAllText(fontContentMgcbFile, mgcbContent);
            }
            else if (add == false)
            {
                fontContentMgcbFileContent = fontContentMgcbFileContent.Replace(mgcbContent, string.Empty);
                _fileService.WriteAllText(fontContentMgcbFile, fontContentMgcbFileContent);
            }
        }

        private float GetSizeForResolution(string fontPath, float baseSize)
        {
            return fontPath switch
            {
                "_720p" => MathF.Round(baseSize * (720f / 1080f), 2),
                "_900p" => MathF.Round(baseSize * (900f / 1080f), 2),
                "_1080p" => baseSize,
                "_1440p" => MathF.Round(baseSize * (1440f / 1080f), 2),
                "_2160p" => MathF.Round(baseSize * (2160f / 1080f), 2),
                _ => baseSize
            };
        }
    }
}
