using DinaGameEngine.Models;
using DinaGameEngine.Models.Project;

using System.Text;

namespace DinaGameEngine.CodeGeneration
{
    public partial class CodeGenerator
    {
        public void GeneratePaletteColors(GameProjectModel gameProjectModel)
        {
            GeneratePaletteColorDesigner(gameProjectModel);
            GeneratePaletteColorUserFile(gameProjectModel);
        }
        private void GeneratePaletteColorDesigner(GameProjectModel gameProjectModel)
        {
            var filePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "PaletteColors.Designer.cs");
            if (_fileService.FileExists(filePath) && !_generatedFileChecker.IsAutoGenerated(filePath))
            {
                _logService.Warning($"Fichier '{filePath}' modifié par l'utilisateur.");
                return;
            }

            var generatedFile = new StringBuilder();
            generatedFile.AppendLine(CodeBuilder.AddAutoGeneratedTag());
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Using
            generatedFile.AppendLine(CodeBuilder.AddUsing("Microsoft.Xna.Framework"));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Namespace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Core.Keys", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class PaletteColors", 1));

            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:PALETTE_COLORS]=", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:PALETTE_COLORS]=", 2));

            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(filePath, generatedFile.ToString());
            _logService.Info($"Fichier 'PaletteColors.Designer.cs' généré.");
        }
        private void GeneratePaletteColorUserFile(GameProjectModel gameProjectModel)
        {
            var filePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "PaletteColors.cs");
            if (_fileService.FileExists(filePath))
            {
                _logService.Warning($"Fichier '{filePath}' déjà existant.");
                return;
            }

            var generatedFile = new StringBuilder();

            //Using
            generatedFile.AppendLine(CodeBuilder.AddUsing("Microsoft.Xna.Framework"));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            // Namespace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Core.Keys", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class PaletteColors", 1));

            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.AddLine("", 2));


            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(filePath, generatedFile.ToString());
            _logService.Info($"Fichier 'PaletteColors.cs' généré.");
        }
        public void AddColor(GameProjectModel gameProjectModel, ColorModel model)
        {
            var designerFilePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "PaletteColors.Designer.cs");
            var sectionParser = CreateSectionParserFor(designerFilePath);
            sectionParser.InsertBeforeZone("PALETTE_COLORS", [$"{CodeBuilder.Indentation(2)}public static readonly Color {model.Key} = new Color({model.R}, {model.G}, {model.B}, {model.A});"]);
            _fileService.WriteAllText(designerFilePath, sectionParser.GetContent());
        }
        public void RemoveColor(GameProjectModel gameProjectModel, ColorModel model)
        {
            var designerFilePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "PaletteColors.Designer.cs");
            var sectionParser = CreateSectionParserFor(designerFilePath);
            sectionParser.RemoveFromZone("PALETTE_COLORS", model.Key);
            _fileService.WriteAllText(designerFilePath, sectionParser.GetContent());
        }
    }
}
