using DinaGameEngine.Models;

using System.Text;

namespace DinaGameEngine.CodeGeneration
{
    public partial class CodeGenerator
    {
        private string _resourceKeysName = "ResourceKeys";
        public void GenerateResourceKeys(GameProjectModel gameProjectModel)
        {
            GenerateResourceKeysDesigner(gameProjectModel);
            //GenerateFontKeysUserFile(gameProjectModel);
        }
        private void GenerateResourceKeysDesigner(GameProjectModel gameProjectModel)
        {
            var filePath = _fileService.Combine(gameProjectModel.RootPath, $"{gameProjectModel.ProjectName}.Core", "Keys", $"{_resourceKeysName}.cs");
            if (_fileService.FileExists(filePath) && !_generatedFileChecker.IsAutoGenerated(filePath))
            {
                _logService.Warning($"Fichier '{filePath}' modifié par l'utilisateur.");
                return;
            }

            var generatedFile = new StringBuilder();
            generatedFile.AppendLine(CodeBuilder.AddAutoGeneratedTag());
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Using
            generatedFile.AppendLine(CodeBuilder.AddUsing("DinaCSharp.Services.Fonts"));
            generatedFile.AppendLine(CodeBuilder.AddUsing("DinaCSharp.Services.Keys"));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Namespace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Core.Keys", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public sealed class {_resourceKeysName} : KeyResolver<{_resourceKeysName}, ResourceTag>", 1));

            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:RESOURCE_KEYS]=", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:RESOURCE_KEYS]=", 2));

            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));

            _fileService.WriteAllText(filePath, generatedFile.ToString());
            _logService.Info($"Fichier '{_resourceKeysName}.cs' généré.");
        }

    }
}
