namespace DinaGameEngine.CodeGeneration
{
    public static class CodeBuilder
    {
        public static string OpenBlock(string content, int level) => $$"""{{Indentation(level)}}{{content}}{{Environment.NewLine}}{{Indentation(level)}}{""";
        public static string CloseBlock(int level) => $$"""{{Indentation(level)}}}""";
        public static string AddLine(string content, int level) => $"{Indentation(level)}{content}";
        public static string AddEmptyLine()=> string.Empty;
        public static string AddUsing(string namespaceName) => $"using {namespaceName};";
        public static string AddPartialMethodDeclaration(string signature, int level) => $"{Indentation(level)}partial {signature}{(signature.EndsWith(';') ? string.Empty : ';')}";
        public static string AddPartialMethod(string signature, int level) => OpenBlock($"partial {signature}", level);
        public static string AddAutoGeneratedTag()
        {
            return """
                   // <auto-generated>
                   //     Ce fichier a été généré automatiquement par Dina Game Engine.
                   //     Toute modification manuelle sera écrasée lors de la prochaine génération.
                   //     -------------------------------------------------------------------------
                   //     This file was automatically generated by Dina Game Engine.
                   //     Any manual changes will be overwritten the next time the file is generated.
                   // </auto-generated>
                   """;
        }
        public static string Indentation(int level) => new string(' ', 4 * level);
    }
}
