using DinaGameEngine.Models;
using DinaGameEngine.Models.Project;

using System.Text;

namespace DinaGameEngine.CodeGeneration
{
    public partial class CodeGenerator
    {
        public void GenerateNewScene(GameProjectModel gameProjectModel, SceneModel scene)
        {
            GenerateSceneDesigner(gameProjectModel, scene);
            GenerateSceneUserFile(gameProjectModel, scene);

            // Ajout de la scène dans Core.Keys.SceneKeys
            UpdateSceneKeys(gameProjectModel, scene);

            // Ajout de la scène dans [GameProjectName].Designer.cs (fonction RegisterScene)
            UpdateGameProjectDesignerScenes(gameProjectModel, scene);
        }
        private void GenerateSceneDesigner(GameProjectModel gameProjectModel, SceneModel scene)
        {
            var projectDesignerFilePath = _fileService.Combine(gameProjectModel.RootPath, "Scenes", $"{scene.Class}.Designer.cs");
            if (_fileService.FileExists(projectDesignerFilePath) && !_generatedFileChecker.IsAutoGenerated(projectDesignerFilePath))
            {
                _logService.Warning($"Fichier '{projectDesignerFilePath}' modifié par l'utilisateur.");
                return;
            }

            var generatedFile = new StringBuilder();
            generatedFile.AppendLine(CodeBuilder.AddAutoGeneratedTag());
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:USINGS]=", 0));
            var usings = new string[]
            {
                "DinaCSharp.Services",
                "DinaCSharp.Services.Scenes",
                "Microsoft.Xna.Framework",
                "Microsoft.Xna.Framework.Graphics",
                $"{gameProjectModel.RootNamespace}.Core.Keys"
            };
            foreach (var ns in usings)
                generatedFile.AppendLine(CodeBuilder.AddUsing(ns));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:USINGS]=", 0));

            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Namespace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Scenes", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class {scene.Class} : Scene", 1));

            // Constructeur
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public {scene.Class}(SceneManager sceneManager) : base(sceneManager)", 2));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // Variables privées
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:FIELDS]=", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:FIELDS]=", 2));

            // Load
            generatedFile.AppendLine(CodeBuilder.OpenBlock("public override void Load()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:COMPONENT_LOAD]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:COMPONENT_LOAD]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("OnLoad();", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // Reset
            generatedFile.AppendLine(CodeBuilder.OpenBlock("public override void Reset()", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:COMPONENT_RESET]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:COMPONENT_RESET]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("OnReset();", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // Update
            generatedFile.AppendLine(CodeBuilder.OpenBlock("public override void Update(GameTime gameTime)", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:COMPONENT_UPDATE]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:COMPONENT_UPDATE]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("OnUpdate(gameTime);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // Draw
            generatedFile.AppendLine(CodeBuilder.OpenBlock("public override void Draw(SpriteBatch spriteBatch)", 2));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[ZONE:COMPONENT_DRAW]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("// =[/ZONE:COMPONENT_DRAW]=", 3));
            generatedFile.AppendLine(CodeBuilder.AddLine("OnDraw(spriteBatch);", 3));
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // Fonctions partielles
            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void OnLoad();", 2));
            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void OnReset();", 2));
            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void OnUpdate(GameTime gameTime);", 2));
            generatedFile.AppendLine(CodeBuilder.AddPartialMethodDeclaration("void OnDraw(SpriteBatch spriteBatch);", 2));


            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));


            _fileService.WriteAllText(projectDesignerFilePath, generatedFile.ToString());
            _logService.Info($"Fichier '{scene.Class}.Designer.cs' généré.");
        }
        private void GenerateSceneUserFile(GameProjectModel gameProjectModel, SceneModel scene)
        {
            var sceneUserFilePath = _fileService.Combine(gameProjectModel.RootPath, $"Scenes", $"{scene.Class}.cs");
            if (_fileService.FileExists(sceneUserFilePath))
            {
                _logService.Warning($"Fichier '{sceneUserFilePath}' déjà existant.");
                return;
            }

            var generatedFile = new StringBuilder();
            var usings = new string[]
            {
                "Microsoft.Xna.Framework",
                "Microsoft.Xna.Framework.Graphics",
            };
            foreach (var ns in usings)
                generatedFile.AppendLine(CodeBuilder.AddUsing(ns));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());

            // Naemspace
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"namespace {gameProjectModel.RootNamespace}.Scenes", 0));

            // Classe
            generatedFile.AppendLine(CodeBuilder.OpenBlock($"public partial class {scene.Class}", 1));

            // OnLoad
            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void OnLoad()", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // OnReset
            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void OnReset()", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // OnUpdate
            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void OnUpdate(GameTime gameTime)", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // OnDraw
            generatedFile.AppendLine(CodeBuilder.AddPartialMethod("void OnDraw(SpriteBatch spriteBatch)", 2));
            generatedFile.AppendLine(CodeBuilder.AddEmptyLine());
            generatedFile.AppendLine(CodeBuilder.CloseBlock(2));

            // Fermeture de la classe
            generatedFile.AppendLine(CodeBuilder.CloseBlock(1));

            // Fermeture du namespace
            generatedFile.AppendLine(CodeBuilder.CloseBlock(0));


            _fileService.WriteAllText(sceneUserFilePath, generatedFile.ToString());


            _logService.Info($"Fichier '{scene.Class}.cs' généré.");
        }
        private void UpdateGameProjectDesignerScenes(GameProjectModel gameProjectModel, SceneModel scene)
        {
            var projectDesignerFilePath = _fileService.Combine(gameProjectModel.RootPath, gameProjectModel.ProjectName, $"{gameProjectModel.ProjectName}.Designer.cs");
            var sectionParserProjectDesignerFile = CreateSectionParserFor(projectDesignerFilePath);
            sectionParserProjectDesignerFile.AddUsingIfMissing($"{gameProjectModel.RootNamespace}.Scenes");
            sectionParserProjectDesignerFile.InsertBeforeZone("REGISTER_SCENE", [$"{CodeBuilder.Indentation(3)}_sceneManager.AddScene(SceneKeys.{scene.Key}, () => new {scene.Class}(_sceneManager));"]);
            _fileService.WriteAllText(projectDesignerFilePath, sectionParserProjectDesignerFile.GetContent());
        }
        private void UpdateSceneKeys(GameProjectModel gameProjectModel, SceneModel scene)
        {
            var sceneKeysFilePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "SceneKeys.cs");
            var sectionParserSceneKeys = CreateSectionParserFor(sceneKeysFilePath);

            sectionParserSceneKeys.InsertBeforeZone("REGISTER_KEY_SCENE", [$"{CodeBuilder.Indentation(2)}public static readonly Key<SceneTag> {scene.Key} = Key<SceneTag>.FromString(\"{scene.Name}\");"]);
            _fileService.WriteAllText(sceneKeysFilePath, sectionParserSceneKeys.GetContent());

        }
        public void RemoveScene(GameProjectModel gameProjectModel, SceneModel scene)
        {
            // Suppression de la scène dans le GameProjectDesigner
            var projectDesignerFilePath = _fileService.Combine(gameProjectModel.RootPath, gameProjectModel.ProjectName, $"{gameProjectModel.ProjectName}.Designer.cs");
            var sectionParserProjectDesigner = CreateSectionParserFor(projectDesignerFilePath);
            sectionParserProjectDesigner.RemoveFromZone("REGISTER_SCENE", scene.Key);
            _fileService.WriteAllText(projectDesignerFilePath, sectionParserProjectDesigner.GetContent());

            // Suppression de la scène dans SceneKeys
            var sceneKeysFilePath = _fileService.Combine(gameProjectModel.RootPath, "Core", "Keys", "SceneKeys.cs");
            var sectionParserSceneKeys = CreateSectionParserFor(sceneKeysFilePath);
            sectionParserSceneKeys.RemoveFromZone("REGISTER_KEY_SCENE", scene.Key);
            _fileService.WriteAllText(sceneKeysFilePath, sectionParserSceneKeys.GetContent());

            // Suppression des fichiers Designer et UserFile de la scène
            var sceneDesignerFilePath = _fileService.Combine(gameProjectModel.RootPath, "Scenes", $"{scene.Class}.Designer.cs");
            _fileService.DeleteFile(sceneDesignerFilePath);
            var sceneUserFilePath = _fileService.Combine(gameProjectModel.RootPath, "Scenes", $"{scene.Class}.cs");
            _fileService.DeleteFile(sceneUserFilePath);
        }

    }
}
