namespace DinaGameEngine.CodeGeneration
{
    public static class CodeBuilder
    {
        public static string OpenBlock(string content, int level) => $$"""{{Indentation(level)}}{{content}}{{Environment.NewLine}}{{Indentation(level)}}{""";
        public static string CloseBlock(int level) => $$"""{{Indentation(level)}}}""";
        public static string AddLine(string content, int level) => $"{Indentation(level)}{content}";
        public static string AddEmptyLine()=> string.Empty;
        public static string AddUsing(string namespaceName) => $"using {namespaceName};";
        public static string AddPartialMethodDeclaration(string signature, int level) => $"{Indentation(level)}partial {signature}{(signature.EndsWith(';') ? string.Empty : ';')}";
        public static string AddPartialMethod(string signature, int level) => OpenBlock($"partial {signature}", level);
        public static string AddAutoGeneratedTag()
        {
            return """
                   // <auto-generated>
                   //     Ce fichier a été généré automatiquement par Dina Game Engine.
                   //     Toute modification manuelle sera écrasée lors de la prochaine génération.
                   //     -------------------------------------------------------------------------
                   //     This file was automatically generated by Dina Game Engine.
                   //     Any manual changes will be overwritten the next time the file is generated.
                   // </auto-generated>
                   """;
        }
        public static string Indentation(int level) => new string(' ', 4 * level);
        public static string SpritefontContent()
        {
            return """
                   <?xml version="1.0" encoding="utf-8"?>
                   <!--
                   This file contains an xml description of a font, and will be read by the XNA
                   Framework Content Pipeline. Follow the comments to customize the appearance
                   of the font in your game, and to change the characters which are available to draw
                   with.
                   -->
                   <XnaContent xmlns:Graphics="Microsoft.Xna.Framework.Content.Pipeline.Graphics">
                     <Asset Type="Graphics:FontDescription">

                       <!--
                       Modify this string to change the font that will be imported.
                       -->
                       <FontName>{0}</FontName>

                       <!--
                       Size is a float value, measured in points. Modify this value to change
                       the size of the font.
                       -->
                       <Size>{1}</Size>

                       <!--
                       Spacing is a float value, measured in pixels. Modify this value to change
                       the amount of spacing in between characters.
                       -->
                       <Spacing>{2}</Spacing>

                       <!--
                       UseKerning controls the layout of the font. If this value is true, kerning information
                       will be used when placing characters.
                       -->
                       <UseKerning>true</UseKerning>

                       <!--
                       Style controls the style of the font. Valid entries are "Regular", "Bold", "Italic",
                       and "Bold, Italic", and are case sensitive.
                       -->
                       <Style>{3}</Style>

                       <!--
                       If you uncomment this line, the default character will be substituted if you draw
                       or measure text that contains characters which were not included in the font.
                       -->
                       <!-- <DefaultCharacter>*</DefaultCharacter> -->

                       <!--
                       CharacterRegions control what letters are available in the font. Every
                       character from Start to End will be built and made available for drawing. The
                       default range is from 32, (ASCII space), to 126, ('~'), covering the basic Latin
                       character set. The characters are ordered according to the Unicode standard.
                       See the documentation for more information.
                       -->
                       <CharacterRegions>
                         <CharacterRegion>
                           <Start>&#32;</Start>
                           <End>&#255;</End>
                         </CharacterRegion>
                       </CharacterRegions>
                     </Asset>
                   </XnaContent>
                   """;
        }
        public static string MgcbFontContent()
        {
            return """
                   #begin {0}
                   /importer:FontDescriptionImporter
                   /processor:FontDescriptionProcessor
                   /processorParam:PremultiplyAlpha=True
                   /processorParam:TextureFormat=Compressed
                   /build:{0}
                   {1}
                   """;
        }
    }
}
