using DinaGameEngine.Abstractions;

namespace DinaGameEngine.Services
{
    public class FileService : IFileService
    {
        private const string AppFolderName = "DinaGameEngine";

        public bool FileExists(string path) => File.Exists(path);
        public bool DirectoryExists(string path) => Directory.Exists(path);
        public void CreateDirectory(string path) => Directory.CreateDirectory(path);
        public string ReadAllText(string path) => File.ReadAllText(path);
        public void WriteAllText(string path, string content)
        {
            var directory = Path.GetDirectoryName(path);
            if (directory == null)
                return;
            if (!DirectoryExists(directory))
                CreateDirectory(directory);
            File.WriteAllText(path, content);
        }

        public string GetAppDataDirectory()
        {
            string appData = Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData);
            return Path.Combine(appData, AppFolderName);
        }
        public void DeleteFile(string path) => File.Delete(path);
        public void CopyFile(string source, string destination) => File.Copy(source, destination);
        public IEnumerable<string> GetFiles(string path, string searchPattern) => Directory.GetFiles(path, searchPattern);

        //public string Combine(string path1, string path2) => Path.Combine(path1, path2);
        public string Combine(params string[] paths) => Path.Combine(paths);
        public void AppendAllText(string path, string content) => File.AppendAllText(path, content);

        public void CreateResxFile(string path, string namespaceName, string className)
        {
            var content = """
        <?xml version="1.0" encoding="utf-8"?>
        <root>
          <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
            <xsd:element name="root" msdata:IsDataSet="true">
            </xsd:element>
          </xsd:schema>
          <resheader name="resmimetype">
            <value>text/microsoft-resx</value>
          </resheader>
          <resheader name="version">
            <value>2.0</value>
          </resheader>
          <resheader name="reader">
            <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
          </resheader>
          <resheader name="writer">
            <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
          </resheader>
        </root>
        """;
            WriteAllText(path, content);
        }

        public void CreateResxDesignerFile(string path, string namespaceName, string className)
        {
            var content = $$"""
        //------------------------------------------------------------------------------
        // <auto-generated>
        //     Ce code a été généré par un outil.
        //     Les modifications apportées à ce fichier peuvent provoquer un comportement
        //     incorrect et seront perdues si le code est régénéré.
        // </auto-generated>
        //------------------------------------------------------------------------------

        namespace {{namespaceName}} {
                    using System;
            using System.Reflection;

            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
            internal class {{className}} {
        
                private static global::System.Resources.ResourceManager resourceMan;
                private static global::System.Globalization.CultureInfo resourceCulture;

                internal {{className}}() {}

                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
                internal static global::System.Resources.ResourceManager ResourceManager {get {
                        if (global::System.Object.ReferenceEquals(resourceMan, null)) {
                            global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("{{namespaceName}}.{{className}}", typeof({{className}}).Assembly);
                            resourceMan = temp;
                        }
                        return resourceMan;
                    }
                }

                [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
                internal static global::System.Globalization.CultureInfo Culture {get { return resourceCulture; }
                    set { resourceCulture = value; }
                }
            }
        }
        """;
            WriteAllText(path, content);
        }
    }
}