using DinaGameEngine.Abstractions;

using System;
using System.Collections.Generic;
using System.Text;

namespace DinaGameEngine.Services
{
    public class GeneratedFileChecker(IFileService fileService) : IGeneratedFileChecker
    {
        private readonly IFileService _fileService = fileService;
        private const string AUTOGENERATED_TAG = "<auto-generated>";

        public bool IsAutoGenerated(string filePath)
        {
            if (!_fileService.FileExists(filePath))
                return false;

            var fileContent = _fileService.ReadAllText(filePath);
            if (string.IsNullOrEmpty(fileContent))
                return false;

            return fileContent.Contains(AUTOGENERATED_TAG);
        }
    }
}
